
create DATABASE VENTAS
LOCATION '/user/main/bd/ventas';

DROP TABLE IF EXISTS VENTAS.CATEGORIA;
create EXTERNAL TABLE VENTAS.CATEGORIA
(
ID STRING,
CATEGORIA STRING,
ID_FAMILIA STRING
)
ROW FORMAT DELIMITED
FIELDS TERMINATED BY ';'
LINES TERMINATED BY '\n'
STORED AS TEXTFILE
tblproperties ("skip.header.line.count"="1");


DROP TABLE IF EXISTS VENTAS.CLIENTE;
create EXTERNAL TABLE VENTAS.CLIENTE
(
ID STRING,
DNI STRING,
NOMBRE STRING,
EDAD INT,
GENERO STRING,
TELEFONO STRING,
EMAIL STRING,
DOMICILIO STRING,
FIDELIZADO STRING
)
ROW FORMAT DELIMITED
FIELDS TERMINATED BY ';'
LINES TERMINATED BY '\n'
STORED AS TEXTFILE
tblproperties ("skip.header.line.count"="1");


DROP TABLE IF EXISTS VENTAS.FAMILIA;
create EXTERNAL TABLE VENTAS.FAMILIA
(
ID STRING,
FAMILIA STRING
)
ROW FORMAT DELIMITED
FIELDS TERMINATED BY ';'
LINES TERMINATED BY '\n'
STORED AS TEXTFILE
tblproperties ("skip.header.line.count"="1");


DROP TABLE IF EXISTS VENTAS.FORMA_PAGO;
create EXTERNAL TABLE VENTAS.FORMA_PAGO
(
ID STRING,
FORMA_PAGO STRING
)
ROW FORMAT DELIMITED
FIELDS TERMINATED BY ';'
LINES TERMINATED BY '\n'
STORED AS TEXTFILE
tblproperties ("skip.header.line.count"="1");


DROP TABLE IF EXISTS VENTAS.PRODUCTO;
create EXTERNAL TABLE VENTAS.PRODUCTO
(
ID STRING,
ID_SUBCATEGORIA STRING,
DESCRIPCION STRING,
PRECIO_UNITARIO DOUBLE,
DESCUENTO DOUBLE
)
ROW FORMAT DELIMITED
FIELDS TERMINATED BY ';'
LINES TERMINATED BY '\n'
STORED AS TEXTFILE
tblproperties ("skip.header.line.count"="1");


DROP TABLE IF EXISTS VENTAS.PUNTO_VENTA;
create EXTERNAL TABLE VENTAS.PUNTO_VENTA
(
ID STRING,
ID_CAJA STRING,
ID_CAJERO STRING,
NOMBRE STRING,
CARGO STRING
)
ROW FORMAT DELIMITED
FIELDS TERMINATED BY ';'
LINES TERMINATED BY '\n'
STORED AS TEXTFILE
tblproperties ("skip.header.line.count"="1");


DROP TABLE IF EXISTS VENTAS.SUB_CATEGORIA;
create EXTERNAL TABLE VENTAS.SUB_CATEGORIA
(
ID STRING,
DESCRIPCION STRING,
ID_CATEGORIA STRING
)
ROW FORMAT DELIMITED
FIELDS TERMINATED BY ';'
LINES TERMINATED BY '\n'
STORED AS TEXTFILE
tblproperties ("skip.header.line.count"="1");


DROP TABLE IF EXISTS VENTAS.TIEMPO;
create EXTERNAL TABLE VENTAS.TIEMPO
(
ID STRING,
DIA INT,
SEMANA INT,
MES INT,
ANIO INT,
FECHA STRING,
NOMBRE_MES STRING,
DIA_SEMANA STRING
)
ROW FORMAT DELIMITED
FIELDS TERMINATED BY ';'
LINES TERMINATED BY '\n'
STORED AS TEXTFILE
tblproperties ("skip.header.line.count"="1");


DROP TABLE IF EXISTS VENTAS.TIENDA;
create EXTERNAL TABLE VENTAS.TIENDA
(
ID STRING,
DIRECCION STRING,
ZONA STRING,
TIPO_FORMATO STRING,
ADMINISTRADOR STRING,
ID_UBIGEO STRING,
NOMBRE STRING
)
ROW FORMAT DELIMITED
FIELDS TERMINATED BY ';'
LINES TERMINATED BY '\n'
STORED AS TEXTFILE
tblproperties ("skip.header.line.count"="1");


DROP TABLE IF EXISTS VENTAS.UBIGEO_TIENDA;
create EXTERNAL TABLE VENTAS.UBIGEO_TIENDA
(
ID STRING,
ID_DEPARTAMENTO INT,
ID_PROVINCIA INT,
ID_DISTRITO INT,
DEPARTAMENTO STRING,
PROVINCIA STRING,
DISTRITO STRING,
ZONAS STRING
)
ROW FORMAT DELIMITED
FIELDS TERMINATED BY ';'
LINES TERMINATED BY '\n'
STORED AS TEXTFILE
tblproperties ("skip.header.line.count"="1");


DROP TABLE IF EXISTS VENTAS.VENTAS_FACT;
create EXTERNAL TABLE VENTAS.VENTAS_FACT
(
ID STRING,
ID_PUNTO_VENTA STRING,
ID_TIEMPO STRING,
ID_PRODUCTO STRING,
IF_FORMA_PAGO STRING,
ID_TIENDA STRING,
ID_CLIENTE STRING,
TIPO_DOCUMENTO STRING,
CANTIDAD DOUBLE,
MONTO_VENTA_BRUTA DOUBLE,
IGV DOUBLE,
MONTO_VENTA_TOTAL DOUBLE
)
ROW FORMAT DELIMITED
FIELDS TERMINATED BY ';'
LINES TERMINATED BY '\n'
STORED AS TEXTFILE
tblproperties ("skip.header.line.count"="1");



